# Generated by Django 5.2.17 on 2026-09-29 17:54

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='empresa_nome_unico_ci')],
            },
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estagio', models.CharField(choices=[('LEAD', 'Lead'), ('CONTATO', 'Contato'), ('PROPOSTA', 'Proposta'), ('GANHO', 'Ganho'), ('PERDIDO', 'Perdido')], db_index=True, default='LEAD', max_length=10)),
                ('motivo_perda', models.TextField(blank=True, default='')),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='comercial.empresa')),
            ],
            options={
                'ordering': ['-atualizado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_externa', models.CharField(max_length=40, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('GERADO', 'Gerado'), ('FALHOU', 'Falhou')], default='PENDENTE', max_length=10)),
                ('numero_erp', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('ultimo_erro_tipo', models.CharField(blank=True, choices=[('', 'Nenhum'), ('TEMPO_ESGOTADO', 'Tempo esgotado'), ('ERRO_SERVICO', 'Erro do serviço'), ('RESPOSTA_INVALIDA', 'Resposta inválida')], default='', max_length=20)),
                ('ultimo_erro', models.TextField(blank=True, default='')),
                ('gerado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('oportunidade', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pedido', to='comercial.oportunidade')),
            ],
        ),
        migrations.AddConstraint(
            model_name='oportunidade',
            constraint=models.CheckConstraint(condition=models.Q(('valor__isnull', True), ('valor__gte', 0), _connector='OR'), name='oportunidade_valor_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='oportunidade',
            constraint=models.CheckConstraint(condition=models.Q(('estagio__in', ['LEAD', 'CONTATO', 'PROPOSTA', 'GANHO', 'PERDIDO'])), name='oportunidade_estagio_valido'),
        ),
        migrations.AddConstraint(
            model_name='oportunidade',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estagio__in', ['GANHO', 'PERDIDO']), ('fechado_em__isnull', False)), models.Q(models.Q(('estagio__in', ['GANHO', 'PERDIDO']), _negated=True), ('fechado_em__isnull', True)), _connector='OR'), name='oportunidade_fechado_em_coerente'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='pedido_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDENTE', 'GERADO', 'FALHOU'])), name='pedido_status_valido'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('gerado_em__isnull', False), ('numero_erp__isnull', False), ('status', 'GERADO')), models.Q(models.Q(('status', 'GERADO'), _negated=True), ('gerado_em__isnull', True), ('numero_erp__isnull', True)), _connector='OR'), name='pedido_gerado_coerente'),
        ),
    ]
